### ISSUE TITLE
Do you have the original code?

### ISSUE THREAD

**Issue by showname2020** [GabrielCSTR/priston-private#1]
After this version is compiled, it cannot run properly. Do you have the original code?

**Comment by gbrlstr** [comment]
> After this version is compiled, it cannot run properly. Do you have the original code?

These files are only for studies of systems that exist in it.
If you want it to work you will have to make several adjustments to the code.

**Comment by showname2020** [comment]
thank you .SQL script is missing, and server-side running files are also missing.

**Comment by showname2020** [comment]
SQL script is missing, and server-side running files are also missing.

**Comment by showname2020** [comment]
Please send me these files，Source,ServerFiles,Client,DBS
